### ISSUE TITLE
Read and save the same document, and find different

### ISSUE THREAD

**Issue by LJjack** [vitoramaral10/excel_facility#1]
[Template.xlsx](https://github.com/vitoramaral10/excel_facility/files/10150385/Template.xlsx)
[Template-save.xlsx](https://github.com/vitoramaral10/excel_facility/files/10150412/Template-save.xlsx)
Question：
After reading this file, save it directly. It is found that the two documents are different.

Test environment:
Testing with Mac OS

**Comment by vitoramaral10** [comment]
This project was a fork of the excel project, as the original project did not support null safety, but it was updated again and compatible with Dart 3.

please change your code to use original package by link

[https://pub.dev/packages/excel](https://pub.dev/packages/excel)
